
const styles = {
  imgIconButton: {
    width: '60px',
    minWidth: '60px',
    height: '60px',
    marginRight: '-10px',
  },
  appMenu: {
    width: 320,
    height: 340,
    padding: 28,
    border: '1px solid #ccc',
    borderColor: 'rgba(0, 0, 0, .2)',
    color: '#000',
    boxShadow: '0 2px 10px rgba(0, 0, 0, .2)',
    outline: 'none',
    overflow: 'hidden',
    borderRadius: 2,
  },
  appMenuItem: {
    flexGrow: 1,
    width: 'calc(33% - 20px)',
    padding: 5,
    display: 'flex',
    flexDirection: 'column',
    position: 'absolute',
    height: 100,
    justifyContent: 'center',
  },
  appMenuItemIcon: {
    width: 55,
    height: 55,
    position: 'relative',
    margin: 0,
    fontSize: 50,
    left: 0,
    textAlign: 'center',
  },
  appMenuItemInner: {
    padding: 0,
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    flexDirection: 'column',
    fontSize: '13px',
    lineHeight: '20px',
  },
  listItem: {

  },
  profileMenu: {
    padding: 0,
    border: '1px solid #ccc',
    borderColor: 'rgba(0, 0, 0, .2)',
    color: '#000',
    boxShadow: '0 2px 10px rgba(0, 0, 0, .2)',
    outline: 'none',
    overflow: 'hidden',
    borderRadius: 2,
  },
  profileMenuInnerContainer: {
    marginTop: '-8px',
  },
  profileMenuTop: {
    background: '#fef9db',
    fontSize: '11px',
    padding: '10px 20px',
    whiteSpace: 'normal',
  },
  mainProfile: {
    display: 'flex',
    padding: '20px',
    flexDirection: 'row',
    alignItems: 'center',
  },
  mainProfileAvatarWrapper: {
    width: 96,
    height: 96,
    padding: 0,
    marginRight: 20,
    borderRadius: '50%',
    overflow: 'hidden',
    position: 'relative',
    cursor: 'pointer',
  },
  mainProfileAvatarIcon: {
    padding: 0,
    width: 96,
    height: 96,
  },
  mainProfileAvatarChange: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    left: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 2,
    textAlign: 'center',
    height: '23px',
    color: 'white',
    fontSize: '11px',
  },
  profileLink: {
    padding: '10px 20px',
    borderTop: '1px solid #ccc',
  },
  profileLinkIcon: {
    width: 48,
    height: 48,
    fontSize: '48px',
    margin: 0,
  },
  footer: {
    borderTop: '1px solid #ccc',
    padding: '10px 20px',
    textAlign: 'right',
    background: '#f5f5f5',
    height: 52,
  },
  logOut: {
    color: '#666',
    border: '1px solid #c6c6c6',
    background: '#f8f8f8',
    width: 80,
    fontSize: '13px',
    borderRadius: '3px',
    float: 'right',
    minHeight: 0,
    lineHeight: '32px',
  },
};

export default styles;
